api/urls.py
from django.urls import path, include
from rest_framework import routers

from api.views import SensorReadingViewSet, SensorReadingCreateView

router = routers.DefaultRouter()
router.register(r'sensor-reading', SensorReadingViewSet)


urlpatterns = [
    path('routers/', include(router.urls)),
    path('sensor-reading-create/', SensorReadingCreateView.as_view(), name='sensor-reading-create'),
]

chart_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from rest_framework.schemas import get_schema_view

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

# API urls
urlpatterns += [
    path('api/v1/', include('api.urls')),
    path('api-schema/', get_schema_view(
        title="Real-time Chart",
        description="API developed to show real-time chart",
    ), name='api-schema'),
    path('docs/', TemplateView.as_view(
        template_name='documentation.html',
        extra_context={'schema_url': 'api-schema'}
    ), name='swagger-ui'),
]

urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)
urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    path('', views.BaseIndexView.as_view(), name='index'),
    path('export_to_csv/', views.export_sensor_data_csv, name='export_sensor_data_csv'),
    # path('start_sensor_reading/', views.start_sensor_reading, name='start_sensor_reading'),
]

core/models.py
from django.db import models


class Setting(models.Model):
    team_id = models.PositiveIntegerField()

    website_title = models.CharField(max_length=50, default="Cansat - Teknofest", blank=True)
    enable_sensor_reading = models.BooleanField(default=False)

    def __str__(self):
        return self.website_title


class SensorReading(models.Model):
    setting = models.ForeignKey('Setting', on_delete=models.PROTECT, default=1, related_name='sensor_readings')

    working_duration = models.PositiveIntegerField(default=0, blank=True)
    number_of_telemetry_packets = models.PositiveIntegerField(default=0, blank=True)
    battery_voltage = models.FloatField(default=0.0, blank=True)
    altitude = models.FloatField(default=0.0, blank=True)
    distance_to_ground = models.FloatField(default=0.0, blank=True)
    velocity = models.FloatField(default=0.0, blank=True)
    temperature = models.FloatField(default=0.0, blank=True)

    no2_level_in_ppm = models.FloatField(default=0.0, blank=True)
    co_level_in_ppm = models.FloatField(default=0.0, blank=True)
    h2_level_in_ppm = models.FloatField(default=0.0, blank=True)

    gps_latitude = models.FloatField(default=0.0, blank=True)
    gps_longitude = models.FloatField(default=0.0, blank=True)
    gps_altitude = models.FloatField(default=0.0, blank=True)

    # logs
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Sensor Readings'
        ordering = ('-created_at',)

    def __str__(self):
        return "%s %s" % (str(self.setting.team_id), str(self.number_of_telemetry_packets))

api/views.py
from core.models import SensorReading
from api.serializers import SensorReadingListSerializer

# Rest Framework Imports
from rest_framework import viewsets, mixins
from rest_framework.generics import GenericAPIView


class SensorReadingViewSet(viewsets.ModelViewSet):
    queryset = SensorReading.objects.all()
    serializer_class = SensorReadingListSerializer


class SensorReadingCreateView(GenericAPIView, mixins.CreateModelMixin):
    queryset = SensorReading.objects.all()
    serializer_class = SensorReadingListSerializer

    def post(self, request, *args, **kwargs):
        print(request.data)
        return self.create(request, *args, **kwargs)

core/views.py
import csv
import logging

from django.views import generic
from django.http import HttpResponse

from core.models import Setting, SensorReading
from chart_project.settings import TEAM_ID

logging.basicConfig(level=logging.INFO)


class BaseIndexView(generic.TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(BaseIndexView, self).get_context_data(**kwargs)

        setting_obj = Setting.objects.first()
        context['team_id'] = setting_obj.team_id if setting_obj else "No Team ID"

        return context


def export_sensor_data_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = f'attachment; filename="{TEAM_ID}_sensor_data.csv"'

    writer = csv.writer(response)

    not_included_fields = ['id', 'created_at', 'updated_at', 'setting']
    model_fields = ['TEAM ID'] + [field.name for field in SensorReading._meta.get_fields()
                                  if field.name not in not_included_fields]

    writer.writerow(model_fields)

    sensor_data = SensorReading.objects.all().order_by('id').values_list(
        'working_duration', 'number_of_telemetry_packets', 'battery_voltage', 'altitude', 'velocity', 'temperature',
        'no2_level_in_ppm', 'co_level_in_ppm', 'h2_level_in_ppm', 'gps_latitude', 'gps_longitude', 'gps_altitude'
    )

    clean_sensor_data = map(lambda x: (TEAM_ID,) + x, sensor_data)

    for sensor_reading in clean_sensor_data:
        writer.writerow(sensor_reading)

    return response

graph_socket/views.py
from django.shortcuts import render

# Create your views here.

api/templates/documentation.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Real-time Chart Project Documentation</title>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
    </head>
    <body>
        <div id="swagger-ui"></div>
        <script src="https://unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
        <script>
            const ui = SwaggerUIBundle({
                url: "{% url schema_url %}",
                dom_id: '#swagger-ui',
                presets: [
                  SwaggerUIBundle.presets.apis,
                  SwaggerUIBundle.SwaggerUIStandalonePreset
                ],
                layout: "BaseLayout"
              })
        </script>
    </body>
</html>

core/templates/base.html
{% load static %}
{% load i18n %}
{% load l10n %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1, initial-scale=1, user-scalable=no">

        {% block meta %}
        {% endblock %}

        {% block title %}
            <title>{{ setting.website_title }}</title>
        {% endblock %}
        <link rel="icon" type="image/x-icon" href="{% static 'assets/images/rvr_logo.jpeg' %}">

        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/charts.css/dist/charts.min.css">
        {% block css %}
        {% endblock %}
        <link rel="stylesheet" href="{% static 'client/css/main.css' %}">

        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        {% block extra_js %}
        {% endblock %}
    </head>

    <body>
{#        {% block header %}#}
{#            <nav class="navbar navbar-expand-lg navbar-light bg-light">#}
{#              <a class="navbar-brand" href="#">Navbar</a>#}
{#              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">#}
{#                <span class="navbar-toggler-icon"></span>#}
{#              </button>#}
{##}
{#              <div class="collapse navbar-collapse" id="navbarSupportedContent">#}
{#                <ul class="navbar-nav mr-auto">#}
{#                  <li class="nav-item active">#}
{#                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>#}
{#                  </li>#}
{#                  <li class="nav-item">#}
{#                    <a class="nav-link" href="#">Link</a>#}
{#                  </li>#}
{#                </ul>#}
{#              </div>#}
{#            </nav>#}
{#        {% endblock %}#}

        <section class="main-body">
            {% block content %}
            {% endblock %}
        </section>

        {% block footer %}
        {% endblock %}

        {% block js %}
        {% endblock %}
    </body>
</html>

core/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load l10n %}

{% block extra_js %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
{% endblock %}

{% block content %}
    <h1 style="color: #585858; text-align: center; margin: 10px 0 10px 0;">{% trans 'Monitoring' %}</h1>
    <div class="chart-row-m0">
        <div class="container">
            <canvas id="battery-voltage-graph" width="277" height="186"></canvas>
        </div>
        <div class="container">
            <canvas id="altitude-graph" width="277" height="186"></canvas>
        </div>
        <div class="container">
            <canvas id="velocity-graph" width="277" height="186"></canvas>
        </div>
        <div class="container">
            <canvas id="temperature-graph" width="277" height="186"></canvas>
        </div>
    </div>
    <div class="main-container">
        <div class="main-left">
            <section class="control-section">
                <h2 style="text-align: center; color: #585858;">{% trans 'Control Panel' %}</h2>
                <button class="control-buttons" id="start-button">{% trans 'Start' %}</button>
                <div class="control-container">
                    <div class="control-group">
                        <button class="control-buttons" id="reset-button">{% trans 'Reset' %}</button>
                    </div>
                    <div class="control-group">
                        <form action="{% url 'core:export_sensor_data_csv' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" id="save-stop-button">{% trans 'Save & Stop' %}</button>
                        </form>
                    </div>
                </div>
            </section>
        </div>
        <div class="main-right">
            <section class="basic-info-section-right">
                <div class="basic-info-container">
                    <div class="basic-info-group">
                        <label for="team-id">{% trans 'Software State' %}</label>
                        <input type="text" id="software-state" readonly value="Off" autocomplete="off">
                    </div>
                    <div class="basic-info-group">
                        <label for="number_of_telemetry_packets">{% trans 'Packet Count' %}</label>
                        <input type="text" id="number_of_telemetry_packets" readonly autocomplete="off">
                    </div>
                    <div class="basic-info-group">
                        <label for="working_duration">{% trans 'Working Duration' %}</label>
                        <input type="text" id="working_duration" readonly autocomplete="off">
                    </div>
                </div>
                <div class="basic-info-container">
                    <div class="basic-info-group">
                        <label for="no2_level_in_ppm">{% trans 'Humidity (%)' %}</label>
                        <input type="text" id="no2_level_in_ppm" readonly autocomplete="off">
                    </div>
                    <div class="basic-info-group">
                        <label for="co_level_in_ppm">{% trans 'Laudness (db)' %}</label>
                        <input type="text" id="co_level_in_ppm" readonly autocomplete="off">
                    </div>
                    <div class="basic-info-group">
                        <label for="h2_level_in_ppm">{% trans 'Distance (m)' %}</label>
                        <input type="text" id="h2_level_in_ppm" readonly autocomplete="off">
                    </div>
                </div>
                <div class="basic-info-container">
                    <div class="basic-info-group">
                        <label for="velocity">{% trans 'Pressure (mBar)' %}</label>
                        <input type="text" id="velocity" readonly autocomplete="off">
                    </div>
                    <div class="basic-info-group">
                        <label for="battery_voltage">{% trans 'Voltage (V)' %}</label>
                        <input type="text" id="battery_voltage" readonly autocomplete="off">
                    </div>
                    <div class="basic-info-group">
                        <label for="altitude">{% trans 'Current (A)' %}</label>
                        <input type="text" id="altitude" readonly autocomplete="off">
                    </div>
                </div>
                <div class="basic-info-container">
                    <div class="basic-info-group">
                        <label for="gps_latitude">{% trans 'GPS Lattitude' %}</label>
                        <input type="text" id="gps_latitude" readonly autocomplete="off">
                    </div>
                    <div class="basic-info-group">
                        <label for="gps_longitude">{% trans 'GPS Longtitude' %}</label>
                        <input type="text" id="gps_longitude" readonly autocomplete="off">
                    </div>
                    <div class="basic-info-group">
                        <label for="gps_altitude">{% trans 'GPS Altitude' %}</label>
                        <input type="text" id="gps_altitude" readonly autocomplete="off">
                    </div>
                </div>
            </section>
        </div>
    </div>
    <div class="chart-row-m0">
        <div class="container">
            <canvas id="no2-graph" width="277" height="186"></canvas>
        </div>
        <div class="container">
            <canvas id="co-graph" width="277" height="186"></canvas>
        </div>
        <div class="container">
            <canvas id="h2-graph" width="277" height="186"></canvas>
        </div>
        <div class="container">
            <canvas id="gps-graph" width="277" height="186"></canvas>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'client/js/graphClass.js' %}"></script>
    <script src="{% static 'client/js/helperFunctions.js' %}"></script>
    <script src="{% static 'client/js/customGraph.js' %}"></script>
{% endblock %}